config/routes.rb
Rails.application.routes.draw do
  get 'bicycles/index/:id' => 'bicycles#index'

  get 'bicycles/category'
  resources :bicycles
  

  resources :orders

  resources :bicycleposts
  resources :bicyclecategories
  devise_for :admins
  	as :admmin do 
  		get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
  		put 'users' => 'devise/registrations#update', :as => 'admin_registration'
  	end
  devise_for :users

  root to: 'bicycleposts#index'
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bicyclecategory.rb
class Bicyclecategory < ApplicationRecord
	has_many :bicycleposts
end

app/controllers/bicyclecategories_controller.rb
class BicyclecategoriesController < ApplicationController
  before_action :set_bicyclecategory, only: [:show, :edit, :update, :destroy]

  # GET /bicyclecategories
  # GET /bicyclecategories.json
  def index
    @bicyclecategories = Bicyclecategory.all
  end

  # GET /bicyclecategories/1
  # GET /bicyclecategories/1.json
  def show
  end

  # GET /bicyclecategories/new
  def new
    @bicyclecategory = Bicyclecategory.new
  end

  # GET /bicyclecategories/1/edit
  def edit
  end

  # POST /bicyclecategories
  # POST /bicyclecategories.json
  def create
    @bicyclecategory = Bicyclecategory.new(bicyclecategory_params)

    respond_to do |format|
      if @bicyclecategory.save
        format.html { redirect_to @bicyclecategory, notice: 'Bicyclecategory was successfully created.' }
        format.json { render :show, status: :created, location: @bicyclecategory }
      else
        format.html { render :new }
        format.json { render json: @bicyclecategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bicyclecategories/1
  # PATCH/PUT /bicyclecategories/1.json
  def update
    respond_to do |format|
      if @bicyclecategory.update(bicyclecategory_params)
        format.html { redirect_to @bicyclecategory, notice: 'Bicyclecategory was successfully updated.' }
        format.json { render :show, status: :ok, location: @bicyclecategory }
      else
        format.html { render :edit }
        format.json { render json: @bicyclecategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bicyclecategories/1
  # DELETE /bicyclecategories/1.json
  def destroy
    @bicyclecategory.destroy
    respond_to do |format|
      format.html { redirect_to bicyclecategories_url, notice: 'Bicyclecategory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bicyclecategory
      @bicyclecategory = Bicyclecategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bicyclecategory_params
      params.require(:bicyclecategory).permit(:name)
    end
end

app/helpers/bicyclecategories_helper.rb
module BicyclecategoriesHelper
end

app/views/bicyclecategories/_form.html.erb
<%= form_with(model: bicyclecategory, local: true) do |form| %>
  <% if bicyclecategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bicyclecategory.errors.count, "error") %> prohibited this bicyclecategory from being saved:</h2>

      <ul>
      <% bicyclecategory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :bicyclecategory_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bicyclecategories/edit.html.erb
<h1>Editing Bicyclecategory</h1>

<%= render 'form', bicyclecategory: @bicyclecategory %>

<%= link_to 'Show', @bicyclecategory %> |
<%= link_to 'Back', bicyclecategories_path %>

app/views/bicyclecategories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bicyclecategories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bicyclecategories.each do |bicyclecategory| %>
      <tr>
        <td><%= bicyclecategory.name %></td>
        <td><%= link_to 'Show', bicyclecategory %></td>
        <td><%= link_to 'Edit', edit_bicyclecategory_path(bicyclecategory) %></td>
        <td><%= link_to 'Destroy', bicyclecategory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bicyclecategory', new_bicyclecategory_path %>

app/views/bicyclecategories/new.html.erb
<h1>New Bicyclecategory</h1>

<%= render 'form', bicyclecategory: @bicyclecategory %>

<%= link_to 'Back', bicyclecategories_path %>

app/views/bicyclecategories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bicyclecategory.name %>
</p>
<%= link_to '商品投稿に戻る', new_bicyclepost_path %> |
<%= link_to 'カテゴリー名編集', edit_bicyclecategory_path(@bicyclecategory) %> |
<%= link_to 'カテゴリーを追加する', bicyclecategories_path %>