config/routes.rb
Rails.application.routes.draw do
  get 'bicycles/index/:id' => 'bicycles#index'

  get 'bicycles/category'
  resources :bicycles
  

  resources :orders

  resources :bicycleposts
  resources :bicyclecategories
  devise_for :admins
  	as :admmin do 
  		get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
  		put 'users' => 'devise/registrations#update', :as => 'admin_registration'
  	end
  devise_for :users

  root to: 'bicycleposts#index'
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bicyclepost.rb
class Bicyclepost < ApplicationRecord
	belongs_to :bicyclecategory

	has_many :order
end

app/controllers/bicycleposts_controller.rb
class BicyclepostsController < ApplicationController
  before_action :set_bicyclepost, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_admin!, only: [:new]
  # GET /bicycleposts
  # GET /bicycleposts.json
  def index
    @bicycleposts = Bicyclepost.page(params[:page])
    @categories = Bicyclecategory.all
  end

  # GET /bicycleposts/1
  # GET /bicycleposts/1.json
  def show
  end

  # GET /bicycleposts/new
  def new
    @bicyclepost = Bicyclepost.new
    @categories = Bicyclecategory.all
  end

  # GET /bicycleposts/1/edit
  def edit
  end

  # POST /bicycleposts
  # POST /bicycleposts.json
  def create
    @bicyclepost = Bicyclepost.new(bicyclepost_params)

    respond_to do |format|
      if @bicyclepost.save
        format.html { redirect_to @bicyclepost, notice: 'Bicyclepost was successfully created.' }
        format.json { render :show, status: :created, location: @bicyclepost }
      else
        format.html { render :new }
        format.json { render json: @bicyclepost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bicycleposts/1
  # PATCH/PUT /bicycleposts/1.json
  def update
    respond_to do |format|
      if @bicyclepost.update(bicyclepost_params)
        format.html { redirect_to @bicyclepost, notice: 'Bicyclepost was successfully updated.' }
        format.json { render :show, status: :ok, location: @bicyclepost }
      else
        format.html { render :edit }
        format.json { render json: @bicyclepost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bicycleposts/1
  # DELETE /bicycleposts/1.json
  def destroy
    @bicyclepost.destroy
    respond_to do |format|
      format.html { redirect_to bicycleposts_url, notice: 'Bicyclepost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bicyclepost
      @bicyclepost = Bicyclepost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bicyclepost_params
      params.require(:bicyclepost).permit(:name, :value, :description, :image, :bicyclecategory_id)
    end
end

app/helpers/bicycleposts_helper.rb
module BicyclepostsHelper
end

app/views/bicycleposts/_form.html.erb
<%= form_with(model: bicyclepost, local: true) do |form| %>
  <% if bicyclepost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bicyclepost.errors.count, "error") %> prohibited this bicyclepost from being saved:</h2>

      <ul>
      <% bicyclepost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :bicyclepost_name %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.number_field :value, id: :bicyclepost_value %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :bicyclepost_description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :bicyclepost_image %>
  </div>

  <div class="field">
    <%= form.label :bicyclecategory_id %>
    <%= form.number_field :bicyclecategory_id, id: :bicyclepost_bicyclecategory_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bicycleposts/edit.html.erb
<h1>Editing Bicyclepost</h1>

<%= render 'form', bicyclepost: @bicyclepost %>

<%= link_to 'Show', @bicyclepost %> |
<%= link_to 'Back', bicycleposts_path %>

app/views/bicycleposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>自転車屋さん</h1>
<%= page_entries_info @bicycleposts %>
<table>
  <thead>
    <tr>
      <th>商品番号</th>
      <th>商品名</th>
      <th>価格</th>
      <th>説明</th>
      <th>画像</th>
      <th>カテゴリー番号</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bicycleposts.each do |bicyclepost| %>
      <tr>
        <td><%= bicyclepost.id %>
        <td><%= bicyclepost.name %></td>
        <td><%= bicyclepost.value %></td>
        <td><%= bicyclepost.description %></td>
        <td><%= bicyclepost.image %></td>
        <td><%= bicyclepost.bicyclecategory_id %></td>
        <td><%= link_to 'Show', bicyclepost %></td>
        <td><%= link_to 'Edit', edit_bicyclepost_path(bicyclepost) %></td>
        <td><%= link_to 'Destroy', bicyclepost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @bicycleposts %>

<br>
<hr>
<p>カテゴリー一覧</p>
<table>
  <tr>
    <th>カテゴリー番号</th>
    <th>カテゴリー名</th>
  </tr>

  <% @categories.each do |obj| %>
  <tr>
    <td><a href="/bicycles/index/<%= obj.id %>"><%= obj.id %></a></td>
    <td><%= obj.name %>
  </tr>
  <% end %>
</table>



<%= link_to 'New Bicyclepost', new_bicyclepost_path %>

app/views/bicycleposts/new.html.erb
<h1>New Bicyclepost</h1>

<%= render 'form', bicyclepost: @bicyclepost %>

<hr>
<p>カテゴリー一覧</p>
<table>
	<tr>
		<th>ID</th>
		<th>Category</th>
	</tr>

	<% @categories.each do |obj| %>
	<tr>
		<td><%= obj.id %></td>
		<td><%= obj.name %>
	</tr>
	<% end %>
</table>

<%= link_to 'カテゴリー編集ページへ', new_bicyclecategory_path %>

<%= link_to '戻る', bicycleposts_path %>

app/views/bicycleposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bicyclepost.name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @bicyclepost.value %>
</p>

<p>
  <strong>Description:</strong>
  <%= @bicyclepost.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @bicyclepost.image %>
</p>

<p>
  <strong>Bicyclecategory:</strong>
  <%= @bicyclepost.bicyclecategory_id %>
</p>

<%= link_to '注文ページへ', new_order_path %>

<%= link_to 'Edit', edit_bicyclepost_path(@bicyclepost) %> |
<%= link_to 'Back', bicycleposts_path %>