config/routes.rb
Rails.application.routes.draw do
  get 'bicycles/index/:id' => 'bicycles#index'

  get 'bicycles/category'
  resources :bicycles
  

  resources :orders

  resources :bicycleposts
  resources :bicyclecategories
  devise_for :admins
  	as :admmin do 
  		get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
  		put 'users' => 'devise/registrations#update', :as => 'admin_registration'
  	end
  devise_for :users

  root to: 'bicycleposts#index'
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SixthEC</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'トップ', root_path %>｜
    <% if user_signed_in? %> 
              
    <%= current_user.email %>がログイン |
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>｜
    <%= link_to 'マイページ', user_path(current_user) %>

    <% elsif admin_signed_in? %>
    <%= current_admin.email %>がログイン |
    <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>｜
    <%= link_to '管理画面', orders_path %>
    <% else %>
    <%= link_to "新規登録", new_user_registration_path %> |
    <%= link_to "ログイン", new_user_session_path %>
      <%= link_to "管理者用ログイン", new_admin_session_path %>
            <% end %>

    <%= yield %>
  </body>
</html>